version: '2.2'
services:
  mariadb:
    image: bitnami/mariadb:11.0
    container_name: moodle_mariadb
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_moodle
      - MARIADB_DATABASE=bitnami_moodle
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
      - MARIADB_ROOT_PASSWORD=toor
      - MARIADB_ROOT_USER=root
    volumes:
      - './mariadb:/bitnami/mariadb:rw'
     #mem_limit: 484m
     #cpus: 1.0

     
  moodle:
    image: docker.io/bitnami/moodle:5.0
    container_name: moodle
    ports:
      - '81:8080' #- '7090:8080'
      - '441:8443'
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - './moodle:/bitnami/moodle:rw'
      - './moodledata:/bitnami/moodledata:rw'
    depends_on:
      - mariadb
      #mem_limit: 256m
      #cpus: 1.0

  phpmyadmin:
    image: arm64v8/phpmyadmin
    container_name: moodle-phpmyadmin
    restart: always
    depends_on:
      - mariadb
    ports:
      - "82:80"
    environment:
      PMA_HOST: mariadb
    mem_limit: 128m
    cpus: 1.0


volumes:
  mariadb:
    driver: local
  moodle:
    driver: local
  moodledata:
    driver: local
