version: '2.2'
services:
  mariadb:
    image: bitnami/mariadb:11.2 #bitnami/mariadb:11.2
    container_name: mariadb_moodle
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_moodle
      - MARIADB_DATABASE=bitnami_moodle
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    volumes:
      - './mariadb:/bitnami/mariadb:rw'
  moodle:
    image: docker.io/bitnami/moodle:5.0 #docker.io/bitnami/moodle:4.3
    container_name: moodle
    ports:
      - '81:8080' #- '7090:8080'
      - '441:8443'
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - './moodle:/bitnami/moodle:rw'
      - './moodledata:/bitnami/moodledata:rw'
    depends_on:
      - mariadb
 #   mem_limit: 256m
 #   cpus: 1.0
 
volumes:
  mariadb:
    driver: local
  moodle:     
    driver: local
  moodledata:     
    driver: local

